### ISSUE TITLE
OSError: [Errno 24] Too many open files: '/dev/i2c-1'

### ISSUE THREAD

**Issue by dmigo** [flyte/pcf8574#1]
First of all thanks for an awesome library!

The problem I have is that after some amount of calls to the api of the library I get this error:  

```
[2018-02-23 11:58:18 +0000] [2093] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/smbus/smbus.py", line 81, in open
OSError: [Errno 24] Too many open files: '/dev/i2c-1'
```

**Comment by flyte** [comment]
Hi @dmigo you're welcome!

Would you be able to give me an example of how you're using the library?

**Comment by dmigo** [comment]
Sure! There is a method, that looks like this:

``` python

def render(address, port, state):
    from pcf8574 import PCF8574
    pcf = PCF8574(1, address)
    pcf.port[port] = state
```

After I call it for some certain amount of times it gives me the error above.

**Comment by flyte** [comment]
I expect the issue is with creating `pcf` on every call. Could you instantiate `pcf` outside of the function instead? Something like this:

```python
from pcf8574 import PCF8574
pcf = PCF8574(1, <your address>)

def render(port, state):
    pcf.port[port] = state
```

**Comment by dmigo** [comment]
Sounds reasonable.
