### ISSUE TITLE
list seems backward

### ISSUE THREAD

**Issue by LGabrielson** [flyte/pcf8574#2]
I'm probably just misunderstanding, but when I enter:
pcf.port = [False, False, False, False, True, True, True, True] I would expect the four least significant bits to be low, and the highest four significant bits to be high.  I'm getting the opposite.  I've tried to reverse the list, but that doesn't seem to work either.  What am I misunderstanding?

Thanks very much,
Leonard Gabrielson

**Comment by oribotic** [comment]
The list isn't backwards, while yes, it may appear to be backwards, there's another possibility, the board you have may have it labelled incorrectly. I checked, and on a low-cost module I have bought from eBay with a PCF8574T, its **the Pins that are labelled backwards**.

**Comment by flyte** [comment]
As depicted in the code, Python lists are least-significant _index_ first, so the following makes sense:

```python
x = [True, False]
x[0] == True
x[1] == False
```

The list needs to be "backwards" compared to how we read binary, since you need to be able to do:

```python
pin = 3
pin3_value = pcf.port[pin]
```

**Comment by dd5xl** [comment]
I'm still in trouble with this: For my HW setup setting port[7]=True acts on P0 of the chip, as does port[0] for P7. It's not a problem to the silk print of my board, I've checked directly on the chip pin.

While the list is LSB first, the order is correct by this piece of code in port.setter:

```
        for i, val in enumerate(value):
            if val:
                new_state |= 1 << 7 - i
```
but according to PCF8574 datasheet data register is MSB first:

<img width="567" height="456" alt="Image" src="https://github.com/user-attachments/assets/d5a14d60-7756-4641-9a36-72cec1a8d2ef" />
